phpcs:
  standard: Drupal

phpmd:
  standard: phpmd.xml

# Php file extensions to parse.
phpqa:
  report: true
  buildDir: /app/reports
  extensions:
    - php
    - inc
    - install
    - module
    - theme
  ignoredFiles: '*\\.css,*\\.md,*\\.txt,*\\.info,*\\.yml,settings.php'

phpcpd:
    minLines: 5
    minTokens: 70
