phpcs:
  # Reference the correct custom ruleset which includes both Drupal and DrupalPractice.
  standard: /app/.phpcs.xml
  # Since now we also have DrupalPractice and its rules are many and all warnings, treat them as non fatal to ease projects' upgrade path.
  ignoreWarnings: true

phpmd:
  standard: phpmd.xml

phpqa:
  report: true
  verbose: true
  buildDir: /app/reports
  extensions:
    - php
    - inc
    - install
    - module
    - theme
  ignoredFiles: '*\\.css,*\\.md,*\\.txt,*\\.info,*\\.yml,settings.php'

phpcpd:
    minLines: 5
    minTokens: 70

phpstan:
  level: 5
  standard: phpstan.neon

security-checker:
    composerLock: drupal/composer.lock
