name: 'End to end tests for the drupalqa docker image'
on:
  pull_request:
    branches:
      - main
env:
  IMAGE_NAME: drupal-qa
  IMAGE_TAG: testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          make build_image CUSTOM_PHP_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}

      - name: Install testing deps
        run: composer install --working-dir=tests --no-interaction --prefer-dist --no-progress --ignore-platform-reqs

      - name: Execute tests
        run: |
          make tests CUSTOM_PHP_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: coverage_reports
          path: reports
          retention-days: 5
