name: 'End to end tests for the drupalqa docker image'
on:
  pull_request:
    branches:
      - main
env:
  IMAGE_NAME: drupal-qa
  IMAGE_TAG: testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --tag ${IMAGE_NAME}:${IMAGE_TAG}

      - name: Install testing deps
        run: cd tests && composer install --no-interaction --prefer-dist --no-progress --ignore-platform-reqs && cd -

      - name: Execute phpqa
        run: |
          docker run --rm -v ${PWD}/tests:/app/drupal -v ${PWD}/reports:/app/reports ${IMAGE_NAME}:${IMAGE_TAG} phpqa --analyzedDirs "drupal/web/modules" --tools "phpcpd:0,phpcs:0,phpmd:0,phpmetrics,phploc,pdepend,parallel-lint:0,phpstan:0,security-checker:0" --buildDir "/app/reports" || true

      - name: diff phpcs
        run: diff tests/expected_reports/checkstyle.xml reports/checkstyle.xml

      - name: diff phpcpd
        run: diff tests/expected_reports/phpcpd.xml reports/phpcpd.xml

      - name: diff phpmd
        run: diff -I '\<pmd version=.*timestamp=.*\>' tests/expected_reports/phpmd.xml reports/phpmd.xml

      - name: diff phpstan
        run: diff tests/expected_reports/phpstan.xml reports/phpstan.xml

      - name: diff security-checker
        run: diff tests/expected_reports/security-checker.html reports/security-checker.html

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: coverage_reports
          path: reports
          retention-days: 5
